// This file is auto-generated by scripts/generate-registry.mjs
// Do not edit this file manually.

import DBSCANVisualizer from '../data/blog/2026/Mar/dbscan/DBSCANVisualizer'

export const animationComponents = {
  DBSCANVisualizer,
}
