// This file is auto-generated by scripts/generate-registry.mjs
// Do not edit this file manually.

import ExampleShowcase from '../data/blog/2026/June/md2pdf/ExampleShowcase'
import DBSCANVisualizer from '../data/blog/2026/Mar/dbscan/DBSCANVisualizer'
import CostCalculator from '../data/blog/2026/May/llm-costing-dimensions/CostCalculator'
import ReasoningChart from '../data/blog/2026/May/llm-costing-dimensions/ReasoningChart'
import TokenizerVisualizer from '../data/blog/2026/May/llm-costing-dimensions/TokenizerVisualizer'

export const animationComponents = {
  ExampleShowcase,
  DBSCANVisualizer,
  CostCalculator,
  ReasoningChart,
  TokenizerVisualizer,
}
